// Writing a checkpoint: the architecture-agnostic half.
//
// Serialization itself lives in src/gguf/, the tensor names and metadata keys
// live in each src/arch/*.ts, and the pieces they share (the general.* block,
// the tokenizer, the quantized-matrix writer) live in src/arch/common.ts. What
// is left here is the companion run script.

import type { ModelConfig } from "../model/arch.ts";

/**
 * A copy-paste-ready bash script for running an exported GGUF with llama.cpp,
 * written alongside the model so the step after a run is obvious. Uses the
 * model's own context length; `$1` overrides the model path for the variants.
 * Base models carry no chat template, so it drives raw completion.
 */
export function llamaRunScript(ggufFile: string, cfg: ModelConfig): string {
  return `#!/usr/bin/env bash
# Auto-generated by gguf-trainer. Run the exported model with llama.cpp.
# Requires llama.cpp built for your GPU (Vulkan, Metal, CUDA). Pass a different
# .gguf as the first argument to run one of the quantized variants.
set -euo pipefail
MODEL="\${1:-${ggufFile}}"

# One-shot completion (base model: no chat template, raw next-token):
llama-cli -m "$MODEL" -c ${cfg.maxSeq} -n 128 -p "Once upon a time"

# Or serve an OpenAI-compatible endpoint:
# llama-server -m "$MODEL" -c ${cfg.maxSeq} --host 127.0.0.1 --port 8080
`;
}
